DROP TABLE IF EXISTS cms.media CASCADE;
DROP TABLE IF EXISTS cms.post_tags CASCADE;
DROP TABLE IF EXISTS cms.post_categories CASCADE;
DROP TABLE IF EXISTS cms.tags CASCADE;
DROP TABLE IF EXISTS cms.categories CASCADE;
DROP TABLE IF EXISTS cms.posts CASCADE;
DROP SCHEMA IF EXISTS cms CASCADE;
