DROP TABLE IF EXISTS auth.activity_logs CASCADE;
DROP TABLE IF EXISTS auth.verification_tokens CASCADE;
DROP TABLE IF EXISTS auth.sessions CASCADE;
DROP TABLE IF EXISTS auth.roles CASCADE;
DROP TABLE IF EXISTS auth.accounts CASCADE;
DROP TABLE IF EXISTS auth.users CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
